### ISSUE TITLE
Remove useless build in extension 

### ISSUE THREAD

**Issue by 118-61-21-230** [mises-id/mises-browser-core#210]
I don't use "Mises(Deprecated)"  extension so give option to remove this extension.it also allowed in private mode it is very dangerous.

![Screenshot_2024-01-21-13-17-45-77_d4b821f22c36211daa9077338f9854d0](https://github.com/mises-id/mises-browser-core/assets/140193418/d20c924c-7c59-479a-88c1-9b07109b4d07)

**Comment by freshlife001** [comment]
yes it will be removed next release
