### ISSUE TITLE
Toolbar Issues 

### ISSUE THREAD

**Issue by 118-61-21-230** [mises-id/mises-browser-core#211]
Shows two toolbar when bottom toolbar is enabled 

![Screenshot_2024-01-21-17-56-08-45_d4b821f22c36211daa9077338f9854d0](https://github.com/mises-id/mises-browser-core/assets/140193418/42bf614c-7d59-4ef3-b85c-cdb06f80be52)

**Comment by freshlife001** [comment]
fixed in #221
