### ISSUE TITLE
Build on the macOS

### ISSUE THREAD

**Issue by Haoxiqiang** [mises-id/mises-browser-core#49]
I want to build Mises on macOS,Can I start with this repo? Where can I get the documentation?

**Comment by freshlife001** [comment]
you need knowledge on node ,yarn, python, ninja, chromium build system to start
here are some steps:
1 clone the repo
2 run 'yarn' to install node dependency
3 run 'yarn browser_init' to setup chromium code base, download dependency and apply all patches
4 run 'yarn build Debug --target_arch arm64 ' to start a build on mac m1/m2, the default platform is your os running
by the way, you need learn how to set up a proxy to build chromium in GFW.
have fun with web3!

**Comment by freshlife001** [comment]
our build system is forked from brave browser, you can find some documents on https://github.com/brave/brave-browser

**Comment by Haoxiqiang** [comment]
I get it.
mises-browser-core is homologous with brave-core
if I want to build it, I should create a project as brave-browser which libraries for handling dependencies and compilation tools.

**Comment by freshlife001** [comment]
> I get it. mises-browser-core is homologous with brave-core if I want to build it, I should create a project as brave-browser which libraries for handling dependencies and compilation tools.

not really, we have merged brave-browser and brave-core into mises-browser-core, so no other repo needed to build mises
